const CAR_STATUS_AVAILABLE = 'Sẵn sàng';
const CAR_STATUS_RENTING = 'Đang thuê';
const CAR_STATUS_MAINTENANCE = 'Bảo trì';
const CAR_STATUS_BOOKED = 'Đặt thuê';
const CAR_STATUSES = [CAR_STATUS_AVAILABLE, CAR_STATUS_RENTING, CAR_STATUS_MAINTENANCE];

const CONTRACT_STATUS_PENDING = 'Chờ xác nhận';
const CONTRACT_STATUS_ACTIVE = 'Đang hiệu lực';
const CONTRACT_STATUS_COMPLETED = 'Đã hoàn thành';
const CONTRACT_STATUS_CANCELLED = 'Đã hủy';
const CONTRACT_STATUSES = [
  CONTRACT_STATUS_PENDING,
  CONTRACT_STATUS_ACTIVE,
  CONTRACT_STATUS_COMPLETED,
  CONTRACT_STATUS_CANCELLED,
];

const INSPECTION_STATUS_VALID = 'Còn hạn';
const INSPECTION_STATUS_EXPIRING = 'Sắp hết hạn';
const INSPECTION_STATUS_EXPIRED = 'Hết hạn';
const INSPECTION_STATUSES = [
  INSPECTION_STATUS_VALID,
  INSPECTION_STATUS_EXPIRING,
  INSPECTION_STATUS_EXPIRED,
];

const MAINTENANCE_STATUS_IN_PROGRESS = 'Đang bảo trì';
const MAINTENANCE_STATUS_COMPLETED = 'Hoàn thành';
const MAINTENANCE_STATUSES = [MAINTENANCE_STATUS_IN_PROGRESS, MAINTENANCE_STATUS_COMPLETED];

const EMPLOYEE_ROLE_ADMIN = 'Admin';
const EMPLOYEE_ROLE_STAFF = 'Nhân viên';
const EMPLOYEE_ROLES = [EMPLOYEE_ROLE_ADMIN, EMPLOYEE_ROLE_STAFF];

const EMPLOYEE_STATUS_ACTIVE = 'Đang hoạt động';
const EMPLOYEE_STATUS_LOCKED = 'Tạm khóa';
const EMPLOYEE_STATUSES = [EMPLOYEE_STATUS_ACTIVE, EMPLOYEE_STATUS_LOCKED];

const PENALTY_TYPE_LATE = 'Phạt trả muộn';
const PENALTY_TYPE_DAMAGE = 'Phạt hỏng hóc';
const PENALTY_TYPE_LATE_AND_DAMAGE = 'Cả trả muộn và hỏng hóc';
const PENALTY_TYPES = [PENALTY_TYPE_LATE, PENALTY_TYPE_DAMAGE, PENALTY_TYPE_LATE_AND_DAMAGE];

const PAYMENT_METHOD_CASH = 'Tiền mặt';
const PAYMENT_METHOD_TRANSFER = 'Chuyển khoản';
const PAYMENT_METHOD_MOMO = 'Momo';
const PAYMENT_METHOD_ZALOPAY = 'ZaloPay';
const PAYMENT_METHODS = [
  PAYMENT_METHOD_CASH,
  PAYMENT_METHOD_TRANSFER,
  PAYMENT_METHOD_MOMO,
  PAYMENT_METHOD_ZALOPAY,
];

module.exports = {
  CAR_STATUS_AVAILABLE,
  CAR_STATUS_RENTING,
  CAR_STATUS_MAINTENANCE,
  CAR_STATUS_BOOKED,
  CAR_STATUSES,
  CONTRACT_STATUS_PENDING,
  CONTRACT_STATUS_ACTIVE,
  CONTRACT_STATUS_COMPLETED,
  CONTRACT_STATUS_CANCELLED,
  CONTRACT_STATUSES,
  INSPECTION_STATUS_VALID,
  INSPECTION_STATUS_EXPIRING,
  INSPECTION_STATUS_EXPIRED,
  INSPECTION_STATUSES,
  MAINTENANCE_STATUS_IN_PROGRESS,
  MAINTENANCE_STATUS_COMPLETED,
  MAINTENANCE_STATUSES,
  EMPLOYEE_ROLE_ADMIN,
  EMPLOYEE_ROLE_STAFF,
  EMPLOYEE_ROLES,
  EMPLOYEE_STATUS_ACTIVE,
  EMPLOYEE_STATUS_LOCKED,
  EMPLOYEE_STATUSES,
  PENALTY_TYPE_LATE,
  PENALTY_TYPE_DAMAGE,
  PENALTY_TYPE_LATE_AND_DAMAGE,
  PENALTY_TYPES,
  PAYMENT_METHOD_CASH,
  PAYMENT_METHOD_TRANSFER,
  PAYMENT_METHOD_MOMO,
  PAYMENT_METHOD_ZALOPAY,
  PAYMENT_METHODS,
};
