

DROP TABLE IF EXISTS CaiDatHeThong;
DROP TABLE IF EXISTS LienHe;
DROP TABLE IF EXISTS PhiPhat;
DROP TABLE IF EXISTS TraXe;
DROP TABLE IF EXISTS BaoTri;
DROP TABLE IF EXISTS AnhDatXe;
DROP TABLE IF EXISTS HopDongThue;
DROP TABLE IF EXISTS DangKiem;
DROP TABLE IF EXISTS KhachHang;
DROP TABLE IF EXISTS Xe;
DROP TABLE IF EXISTS NhanVien;

CREATE TABLE NhanVien (
  MaNV VARCHAR(20) PRIMARY KEY,
  HoTen VARCHAR(100) NOT NULL,
  SDT VARCHAR(20) NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE,
  ChucVu VARCHAR(30) NOT NULL,
  MatKhau VARCHAR(255) NOT NULL,
  TrangThai VARCHAR(30) NOT NULL DEFAULT 'Đang hoạt động',
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_nhanvien_chucvu
    CHECK (ChucVu IN ('Admin', 'Nhân viên'))
);

CREATE TABLE Xe (
  MaXe VARCHAR(20) PRIMARY KEY,
  BienSo VARCHAR(20) NOT NULL UNIQUE,
  TenXe VARCHAR(100) NOT NULL,
  LoaiXe VARCHAR(50) NOT NULL,
  HangXe VARCHAR(50) NOT NULL,
  NamSanXuat INT NOT NULL,
  GiaThue DECIMAL(15, 2) NOT NULL,
  NhienLieu VARCHAR(30) NOT NULL,
  SoCho INT NOT NULL,
  TrangThai VARCHAR(20) NOT NULL,
  HinhAnh VARCHAR(255),
  GhiChu VARCHAR(255),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_xe_trangthai
    CHECK (TrangThai IN ('Sẵn sàng', 'Đang thuê', 'Bảo trì'))
);

CREATE TABLE DangKiem (
  MaDK VARCHAR(20) PRIMARY KEY,
  MaXe VARCHAR(20) NOT NULL,
  NgayDK DATE NOT NULL,
  HanDK DATE NOT NULL,
  TrangThai VARCHAR(30) NOT NULL,
  GhiChu VARCHAR(255),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_dangkiem_trangthai
    CHECK (TrangThai IN ('Còn hạn', 'Sắp hết hạn', 'Hết hạn')),
  CONSTRAINT fk_dangkiem_xe
    FOREIGN KEY (MaXe) REFERENCES Xe(MaXe)
    ON DELETE CASCADE
);

CREATE TABLE KhachHang (
  MaKH VARCHAR(20) PRIMARY KEY,
  HoTen VARCHAR(100) NOT NULL,
  CCCD VARCHAR(20) UNIQUE,
  SDT VARCHAR(20) NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE,
  MatKhau VARCHAR(255) NOT NULL,
  DiaChi VARCHAR(255),
  BangLai VARCHAR(50),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE HopDongThue (
  MaHD VARCHAR(20) PRIMARY KEY,
  MaKH VARCHAR(20) NOT NULL,
  MaXe VARCHAR(20) NOT NULL,
  NgayThue DATE NOT NULL,
  NgayTraDuKien DATE NOT NULL,
  DiemDon VARCHAR(255) NOT NULL,
  TienCoc DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TongTien DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TrangThai VARCHAR(30) NOT NULL DEFAULT 'Chờ xác nhận',
  GhiChu VARCHAR(255),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_hopdong_trangthai
    CHECK (TrangThai IN ('Chờ xác nhận', 'Đang hiệu lực', 'Đã hoàn thành', 'Đã hủy')),
  CONSTRAINT fk_hopdong_khachhang
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
  CONSTRAINT fk_hopdong_xe
    FOREIGN KEY (MaXe) REFERENCES Xe(MaXe)
);

CREATE TABLE AnhDatXe (
  MaAnh VARCHAR(20) PRIMARY KEY,
  MaHD VARCHAR(20) NOT NULL,
  DuongDan VARCHAR(255) NOT NULL,
  TenTep VARCHAR(255),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_anhdatxe_hopdong
    FOREIGN KEY (MaHD) REFERENCES HopDongThue(MaHD)
    ON DELETE CASCADE
);

CREATE TABLE TraXe (
  MaTraXe VARCHAR(20) PRIMARY KEY,
  MaHD VARCHAR(20) NOT NULL UNIQUE,
  NgayTraXe DATE NOT NULL,
  TinhTrangXe VARCHAR(255),
  SoNgayThueThucTe INT NOT NULL,
  TongTienThue DECIMAL(15, 2) NOT NULL,
  TienCoc DECIMAL(15, 2) NOT NULL DEFAULT 0,
  SoTienConLai DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TongTienThanhToan DECIMAL(15, 2) NOT NULL DEFAULT 0,
  HinhThucThanhToan VARCHAR(30) NOT NULL,
  GhiChu VARCHAR(255),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_traxe_hinhthuc
    CHECK (HinhThucThanhToan IN ('Tiền mặt', 'Chuyển khoản', 'Momo', 'ZaloPay')),
  CONSTRAINT fk_traxe_hopdong
    FOREIGN KEY (MaHD) REFERENCES HopDongThue(MaHD)
    ON DELETE CASCADE
);

CREATE TABLE PhiPhat (
  MaPP VARCHAR(20) PRIMARY KEY,
  MaTraXe VARCHAR(20) NOT NULL,
  LoaiPhiPhat VARCHAR(50) NOT NULL,
  SoTienPhat DECIMAL(15, 2) NOT NULL,
  GhiChu VARCHAR(255),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_phiphat_loai
    CHECK (LoaiPhiPhat IN ('Phạt trả muộn', 'Phạt hỏng hóc', 'Cả trả muộn và hỏng hóc')),
  CONSTRAINT fk_phiphat_traxe
    FOREIGN KEY (MaTraXe) REFERENCES TraXe(MaTraXe)
    ON DELETE CASCADE
);

CREATE TABLE BaoTri (
  MaBaoTri VARCHAR(20) PRIMARY KEY,
  MaXe VARCHAR(20) NOT NULL,
  NgayBaoTri DATETIME NOT NULL,
  NoiDung VARCHAR(255) NOT NULL,
  ChiPhi DECIMAL(15, 2) NOT NULL,
  TrangThai VARCHAR(30) NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_baotri_trangthai
    CHECK (TrangThai IN ('Đang bảo trì', 'Hoàn thành')),
  CONSTRAINT fk_baotri_xe
    FOREIGN KEY (MaXe) REFERENCES Xe(MaXe)
);

CREATE TABLE LienHe (
  MaLH INT AUTO_INCREMENT PRIMARY KEY,
  HoTen VARCHAR(100) NOT NULL,
  SDT VARCHAR(20) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  NoiDung TEXT NOT NULL,
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'Mới',
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_lienhe_trangthai
    CHECK (TrangThai IN ('Mới', 'Đã phản hồi'))
);

CREATE TABLE CaiDatHeThong (
  MaCaiDat INT PRIMARY KEY DEFAULT 1,
  TenCongTy VARCHAR(150) NOT NULL,
  SoDienThoai VARCHAR(30) NOT NULL,
  EmailLienHe VARCHAR(100) NOT NULL,
  DiaChi VARCHAR(255) NOT NULL,
  ThongBaoEmail BOOLEAN NOT NULL DEFAULT TRUE,
  CanhBaoDangKiem BOOLEAN NOT NULL DEFAULT TRUE,
  CanhBaoHopDong BOOLEAN NOT NULL DEFAULT TRUE,
  SoNgayCanhBaoDangKiem INT NOT NULL DEFAULT 30,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
